-- ─────────────────────────────────────────────
-- Migration 021: Contact Normalization Flags
-- Adds new flag_category values for normalization
-- Note: flag_category is VARCHAR, not ENUM, so no ALTER TYPE needed
-- Applied via: npx tsx scripts/migrate.ts
-- ─────────────────────────────────────────────

-- flag_category is already VARCHAR(50) from migration 001
-- New values 'industry-unmatched' and 'jobtitle-unmatched' are automatically
-- accepted since there's no ENUM constraint.
-- This migration is intentionally empty — it exists for documentation purposes.
